### PR TITLE
Specify watchman dependency

### PR DESCRIPTION
**Pull request by amitsaha**

### CODE REVIEW

**Comment by jgavris** [comment]
Thanks for the PR! The dependency is already specified in the homebrew formula, and is installed for you when installing from the tap. I hope to have this in homebrew core soon.

https://github.com/jgavris/rs-git-fsmonitor/blob/master/Formula/rs-git-fsmonitor.rb#L8

Are you proposing installation instructions for other platforms?

**Comment by amitsaha** [comment]
@jgavris Yeah, since I couldn't find any mention of it, when I tried it to run on Windows I thought it is a good idea to state in the README. Anyone not using `brew` to install it will benefit as well I think.

**Comment by amitsaha** [comment]
> Are you proposing installation instructions for other platforms?

I could update my PR with it with some basic instructions:

```
$ git clone ..
$ cargo build ..
...
```

Would you like me to do that?

**Comment by jgavris** [comment]
Sure! If you could make a section for installation on Windows, that would be great. Is there a good package manager out there for Windows that could provide the `brew install` experience?

**Comment by jgavris** [comment]
Homebrew 2.0 now supports Linux and Windows. Have you tried it out? I should update the formula to allow building from source on those platforms.

**Comment by themightychris** [comment]
I don't work on a windows box myself, but it seems like [Chocolatey](https://chocolatey.org/) is the way to deliver a brew-like experience for Windows

**Comment by SuperSandro2000** [comment]
Can this just be added in one form or another? I don't plan to use brew anytime soon and it is a nice little info to know.

**Comment by jgavris** [comment]
Sure thing! I've just modified it a little bit since Habitat instructions were added after this PR was created.

**Pull request merged**
