### PR TITLE
Support v2 of the Git hook

### PR DESCRIPTION
**Pull request by mrkline**
Sorry for the delay in trying to get this upstream! I just saw #20 and its mention of the branch I had on my fork. I'd argue the following:

1. It's not worth to pull in a command line parser
   (and all its dependencies) for a program with two args,
   especially when the type of the second varies on the value of the
   first.

2. We should support both V1 and V2 of the hooks so that this is useful
   to users with an older version of Git as well. It's pretty simple to do so.

### CODE REVIEW

**Comment by jgavris** [comment]
I agree about not needing `StructOpt`...though at the time that wasn't the case.

I gave a go at this myself and I am running into the same issue I see on this build / branch. 

>Error: Watchman failed for an unexpected reason invalid clockspec

```
jgavris in ~/code/rs-git-fsmonitor on (HEAD detached at mrkline/hook-v2)
λ watchman --version
4.9.0
jgavris in ~/code/rs-git-fsmonitor on (HEAD detached at mrkline/hook-v2)
λ git --version
git version 2.26.0
λ git config core.fsmonitorhookversion 2
jgavris in ~/code/rs-git-fsmonitor on (HEAD detached at mrkline/hook-v2)
λ cargo build && time git status
   Compiling rs-git-fsmonitor v0.2.0 (/Users/jgavris/code/rs-git-fsmonitor)
    Finished dev [unoptimized + debuginfo] target(s) in 1.42s
Error: Watchman failed for an unexpected reason invalid clockspec
HEAD detached at mrkline/hook-v2
nothing to commit, working tree clean

real	0m0.428s
user	0m0.012s
sys	0m0.017s
```

Is this working for you?

**Comment by jgavris** [comment]
Hm, it works on a repo that has never had the monitor / hook set before (I tested on `git/git` for fun). What's the graceful way to upgrade? Can the hook actually handle that, is there a way to reset the internal state of the monitor from the outside?

**Comment by mrkline** [comment]
IIRC, I was able to get things back into a good state by removing the watch on the directory with `watchman watch-del`. I'd rather not build that into hook, since the issue seems very ephemeral - it should only pop up when:

1. You've just upgraded this hook from v1 to v2
2. You've already got a Watchman watch on a Git repo.

**Comment by wwwjfy** [comment]
Coming back to check out the status. :)

@jgavris I met that error `invalid clockspec` once. In my case, it was because when the token was an integer the value passed to `since` was a string. Need to parse it as integer in the json query to watchman.

**Comment by jgavris** [comment]
@mrkline Deleting the watch didn't end up working for me to get into the 'good state'. Also those conditions would probably mean everyone who's using this tool at the moment. What is working for me on the few repos I tried is to parse the token as either a string clock id, or a number epoch timestamp in the v2 hook. I'm happy to merge this as is and change that afterwards.

**Review by jgavris — APPROVED** [review]

**Pull request merged**
